version: '3.8'

volumes:
  oscs_tt-postgres:

services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=oscs_tt'
      - 'POSTGRES_USER=oscs_tt'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - 'oscs_tt-postgres:/var/lib/postgresql/data'
  server:
    build:
      context: './server'
      target: 'develop-stage'
    depends_on:
      - 'postgres'
    # env_file:
    #   - ./server/.env
    ports:
      - '8081:8081'
    volumes:
      - './server/src:/app/src'
    command: '/bin/sh -c "yarn serve"'
  client:
    build:
      context: './client'
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - './client/src:/app/src'
      - './client/public:/app/public'
      - './client/tests:/app/tests'
    command: '/bin/sh -c "yarn start"'
