scalar DateTime

type AuthData {
  id: ID
  email: String
  name: String
  accessToken: String
  accessTokenExpiry: DateTime
  refreshTokenExpiry: DateTime
}

extend type Query {
  authData: AuthData!
}
